CREATE TABLE TBL_PARTES (
ID_PARTE SERIAL PRIMARY KEY,
DETALHE VARCHAR(255),
NOME VARCHAR(2000),
APAGADO INT,
DATACAD TIMESTAMP,
ID_LINHA INT NOT NULL,
FOREIGN KEY (ID_LINHA)
	REFERENCES processostf_lote_linha(ID_LINHA)
)


CREATE TABLE TBL_ANDAMENTOS (
ID_ANDAMENTO SERIAL PRIMARY KEY,
TITULO VARCHAR(2000),
TEXTO TEXT,
DATA TIMESTAMP,
APAGADO INT,
DATACAD TIMESTAMP,
ID_LINHA INT NOT NULL,
FOREIGN KEY (ID_LINHA)
	REFERENCES processostf_lote_linha(ID_LINHA)
)


CREATE TABLE TBL_DECISOES (
ID_DECISAO SERIAL PRIMARY KEY,
TITULO VARCHAR(2000),
TEXTO TEXT,
DATA TIMESTAMP,
APAGADO INT,
DATACAD TIMESTAMP,
ID_LINHA INT NOT NULL,
FOREIGN KEY (ID_LINHA)
	REFERENCES processostf_lote_linha(ID_LINHA)
)



CREATE TABLE TBL_DOCUMENTOS (
ID_DOCUMENTO SERIAL PRIMARY KEY,
FILE_PATH VARCHAR(2000),
NAME VARCHAR(2000),
APAGADO INT,
DATACAD TIMESTAMP,
ID_LINHA INT NOT NULL,
FOREIGN KEY (ID_LINHA)
	REFERENCES processostf_lote_linha(ID_LINHA)
)